// Shared quiz fetching used by both the practice quiz and final-chapter quiz.
// English quizzes come from the backend; Burmese quizzes are generated by Gemini.
import axios from "axios";
import { API_BASE_URL } from "@/lib/env";
import { generateQuiz, type Language, type QuizQuestion } from "@/lib/gemini";

export type { QuizQuestion } from "@/lib/gemini";

export interface FetchQuizParams {
  subject: string | null;
  chapter: string | null;
  topic: string | null;
  option: string | null;
  language: Language;
}

export async function fetchQuizQuestions({
  subject,
  chapter,
  topic,
  option,
  language,
}: FetchQuizParams): Promise<QuizQuestion[]> {
  if (language === "my") {
    return generateQuiz({
      subject: subject ?? "",
      chapter: chapter ?? "",
      topic: topic ?? "",
      level: option ?? "intermediate",
      language,
    });
  }

  const res = await axios.get(`${API_BASE_URL}/api/quizes`, {
    params: { subject, chapter, topic, option },
  });

  let parsed: unknown = res.data?.quizes;
  if (typeof parsed === "string") {
    try {
      parsed = JSON.parse(parsed);
    } catch {
      return [];
    }
  }
  return Array.isArray(parsed) ? (parsed as QuizQuestion[]) : [];
}
