// Shared quiz fetching used by both the practice quiz and final-chapter quiz.
// All quizzes — English and Burmese — are generated by Gemini via the server-side
// proxy (see src/lib/gemini.ts and /api/gemini).
import { generateQuiz, type Language, type QuizQuestion } from "@/lib/gemini";

export type { QuizQuestion } from "@/lib/gemini";

export interface FetchQuizParams {
  subject: string | null;
  chapter: string | null;
  topic: string | null;
  option: string | null;
  language: Language;
}

export async function fetchQuizQuestions({
  subject,
  chapter,
  topic,
  option,
  language,
}: FetchQuizParams): Promise<QuizQuestion[]> {
  return generateQuiz({
    subject: subject ?? "",
    chapter: chapter ?? "",
    topic: topic ?? "",
    level: option ?? "intermediate",
    language,
  });
}
