import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { useAuth } from "@/lib/auth";
import { User } from "lucide-react";

export const Topbar = () => {
  const { user } = useAuth();

  return (
    <header className="h-16 border-b bg-background/60 backdrop-blur supports-[backdrop-filter]:bg-background/40 sticky top-0 z-10">
      <div className="container h-full flex items-center justify-between gap-4">
        <div className="flex-1 max-w-2xl" />
        <div className="flex items-center gap-3">
          <Dialog>
            <DialogTrigger asChild>
              <Button variant="soft">AI powered by Gemini</Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Powered by Gemini</DialogTitle>
                <DialogDescription>
                  StudyMateAI uses Google Gemini to generate smart, human-like
                  answers and quizzes — in English and Burmese.
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-3 text-sm text-muted-foreground leading-relaxed">
                <p>
                  Responses are generated by Google's Gemini models, one of the
                  most advanced families of large language models available.
                </p>
                <p>
                  For production use, API keys should be proxied through a secure
                  backend rather than exposed in the frontend.
                </p>
              </div>
            </DialogContent>
          </Dialog>

          <Dialog>
            <DialogTrigger asChild>
              <Avatar
                className="cursor-pointer"
                aria-label="Open student profile"
              >
                <AvatarFallback>
                  <User className="w-6 h-6 text-gray-500" />
                </AvatarFallback>
              </Avatar>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Student Profile</DialogTitle>
                <DialogDescription>Your account details.</DialogDescription>
              </DialogHeader>
              <div className="flex items-center gap-3">
                <div className="rounded-full bg-primary/10 text-primary h-10 w-10 flex items-center justify-center">
                  <User className="w-6 h-6" />
                </div>
                <div>
                  <div className="font-medium">
                    {user?.displayName ?? "Student"}
                  </div>
                  {user?.email && (
                    <p className="text-sm text-muted-foreground">
                      {user.email}
                    </p>
                  )}
                </div>
              </div>
            </DialogContent>
          </Dialog>
        </div>
      </div>
    </header>
  );
};

export default Topbar;
